### PR TITLE
#to_json(:lower_camel_case) generates camel cased keys

### PR DESCRIPTION
**Pull request by aslakhellesoy**
This is a fix for #408

I wasn't sure where to update the documentation - please let me know if you require more changes.

### CODE REVIEW

**Comment by film42** [comment]
Thanks for this PR! Don't worry about the 1.9.3 failure. We should probably drop 1.9.3 support.

**Comment by aslakhellesoy** [comment]
Thanks for merging so quickly! I see you released 3.10.3, but `CHANGES.md` doesn't reflect it.

**Comment by film42** [comment]
Thanks for the reminder! Totally spaced. I'll update CHANGES once I merge my PR that updates travis and gets CI passing again.

**Comment by aslakhellesoy** [comment]
I also believe you need to create a new `3-11-stable` maintenance branch now eh? :-) Life as an open source contributor...

**Pull request merged**
