### PR TITLE
Add support for custom service options

### PR DESCRIPTION
**Pull request by embark**
cc @film42 @nerdrew @zanker @abrandoned 

second to last option PR

### CODE REVIEW

**Comment by film42** [comment]
Waiting on travis but this looks 👍 to me.

**Comment by embark** [comment]
Thanks! The jruby flaky rpc test seems to have fired again...

**Comment by film42** [comment]
Restarted!

**Comment by film42** [comment]
:shipit:

**Comment by embark** [comment]
Yess! I'll fast follow with the last :)

**Pull request merged**
