### PR TITLE
refresh well known protos: descriptor.proto, plugin.proto

### PR DESCRIPTION
**Pull request by nerdrew**
from:
https://raw.githubusercontent.com/google/protobuf/master/src/google/protobuf/descriptor.proto
https://raw.githubusercontent.com/protocolbuffers/protobuf/master/src/google/protobuf/compiler/plugin.proto

### CODE REVIEW

**Review by cheister — APPROVED** [review]

**Comment by nerdrew** [comment]
bumping this PR cc @film42

**Comment by film42** [comment]
This all looks great. I added the plug-in enum to master, but it shows up here again. Let me make sure the diff is right locally.

**Comment by film42** [comment]
Diff on github is a bit strange, but comparing it locally shows this is good to go.

**Comment by film42** [comment]
Released! Thanks, @nerdrew !

**Pull request merged**
