### PR TITLE
Fix "NameError: uninitialized constant Protobuf::Rpc::Protobuf::Socketrpc"

### PR DESCRIPTION
**Pull request by liluo**
Fix "NameError: uninitialized constant Protobuf::Rpc::Protobuf::Socketrpc"

### CODE REVIEW

**Comment by liluo** [comment]
@film42

**Comment by liveh2o** [comment]
It looks like the Rubocop upgrade fixed the no method error, but now a bunch of cops are failing. We need the updated Rubocop version, but I don't think we want all of those cops turned on right now. If you want to disable the new cops and update here, we can merge it in. Otherwise, I can update Rubocop in master and you can rebase.

**Comment by film42** [comment]
I agree with @liveh2o . If you wouldn't mind disabling the failing cops, I would love to merge this.

**Comment by abrandoned** [comment]
pulled into master

**Pull request closed without merging**
