### PR TITLE
Field values should be stored via their fully qualified names

### PR DESCRIPTION
**Pull request by embark**
This fixes a bug where ::Protobuf::Message#{simple_field_name}! would return nil rather than the value of the field, if the field was an extension.
This also fixes a bug where ::Protobuf::Message.field?(name) would always return false if name was the fully qualified name of an extension.

CC @nerdrew @film42 @liveh2o @zachmargolis

### CODE REVIEW

**Comment by embark** [comment]
**IMPORTANT NOTE**: This as-is currently changes the behavior of `::Protobuf::Message#to_hash`:

Before:
```
pry(main)> ::Test::Resource.new(:ext_is_searchable => true).to_hash
=> {:ext_is_searchable=>true}
```

After:
```
pry(main)> ::Test::Resource.new(:ext_is_searchable => true).to_hash
=> {:".test.Searchable.ext_is_searchable"=>true}
```

Any ideas on what the best way to get around this is, if that is desired? We could make `to_hash` be passed an optional parameter, or have a different method entirely that uses fully qualified names in the hash.

**Comment by embark** [comment]
Also I expect tests to fail until #310 is merged

**Comment by zachmargolis** [comment]
LGTM!

**Comment by film42** [comment]
Looks like tests are failing.

**Comment by embark** [comment]
@film42 Yes, tests will fail until  #310 is merged because of that bug

**Comment by film42** [comment]
Sorry! Early morning code reviews be like.. :grin: .

**Comment by embark** [comment]
No worries, thanks for the review :)

**Comment by film42** [comment]
Just merged #310.

**Comment by film42** [comment]
:shipit: :tada: :shipit: :tada: :shipit:

**Comment by film42** [comment]
`3.7.0.pre0` has been released.

**Comment by embark** [comment]
Awesome!!

**Pull request merged**
