### PR TITLE
use a modern fork of the middleware gem

### PR DESCRIPTION
**Pull request by nerdrew**
cc @embark

### CODE REVIEW

**Comment by nerdrew** [comment]
The middleware gem looks unmaintained. This gem is a fork that has merged helpful PRs. https://github.com/Ibsciss/ruby-middleware

**Comment by embark** [comment]
Nice, thanks!

**Comment by film42** [comment]
I'm pretty hesitant to merge something like this since our team has a number of projects using the existing middleware gem. I wish the maintainer had renamed it to something else. I imagine this would introduce a number of conflicts depending on which gem loads first.

**Comment by nerdrew** [comment]
Yes, the gems are mutually exclusive. The new gem is a superset of functionality it seems. The old gem seems to disregard return values which seems unintuitive for a middleware stack.

**Comment by film42** [comment]
Yeah, that's unintuitive, but we can't swap out a dependency with a conflicting name. That's a breaking change with zero discoverability. A while back I forked `middleware` to support variadic args and switched the name to avoid a collision: https://github.com/film42/midler. If this were the case, we could weight pros and cons, but since it's not the case, I can't merge this.

Thanks for opening a PR though @nerdrew . I'm glad someone is trying to maintain middleware.

**Pull request closed without merging**
