### PR TITLE
Ensure bundler is at the latest version to make travis pass

### PR DESCRIPTION
**Pull request by film42**
Other github projects have seen the failing bundler issue and this is how they fixed it:

pdfkit/pdfkit#347
increments/qiita-markdown#24

Thanks @RKushnir for figuring it out.

cc @mmmries @brianstien @abrandoned @localshred

### CODE REVIEW

**Comment by mmmries** [comment]
@film42 looks like the travis logs are now available the only failure I am seeing is that our expectation for how `jruby` handles the `hostname` stuff is a bit off: https://travis-ci.org/ruby-protobuf/protobuf/jobs/103729876#L1024-L1030

**Comment by mmmries** [comment]
@film42 I had to fix this in rspec_rabl with `gem install bundle -v 1.10.6` https://github.com/mmmries/rspec_rabl/blob/79c6c60d713e06dbba40a8d3dde5a8fd61bb34d7/.travis.yml#L11

The latest bundler just doesn't install the local gem correctly. Not sure why, but I downgraded to fix for now

**Comment by film42** [comment]
@mmmries I just changed the spec to use ruby's `::Socket.gethostname` instead of the OS `hostname`, which was what Protobuf is doing. Comparing ruby vs the OS is a redundant test.

**Comment by mmmries** [comment]
:+1: for not using the system `hostname` for our tests. That can obviously change based on which host the tests run on. I'l slightly concerned that we may have been expecting `Socket.hostname` to return only the last part of the fully-qualified hostname.

@localshred do you know if using the fully-qualified hostname from `Socket.hostname` will be a problem for us?

**Pull request merged**
