### PR TITLE
Add support for custom enum options

### PR DESCRIPTION
**Pull request by embark**
cc @film42 @abrandoned @nerdrew @zanker 
Just 4 more short ones!!

### CODE REVIEW

**Comment by embark** [comment]
Can someone re-run the jruby? Seems unrelated, but I don't have a button to rerun the build

**Comment by film42** [comment]
@embark Just restarted the jruby build.

**Comment by film42** [comment]
Code looks great.. just waiting on the build now.

**Comment by film42** [comment]
:shipit:

**Pull request merged**
