### PR TITLE
Allow Message#each_field to return an enumerator

### PR DESCRIPTION
**Pull request by RKushnir**

### CODE REVIEW

**Comment by mmmries** [comment]
This change looks good, but it looks like we are having bundler issues when building in travis. If you can get travis happy I'll gladly add my :+1: to this

**Comment by RKushnir** [comment]
@mmmries Looks like someone was able to solve it by updating rubygems and bundler. 
https://github.com/pdfkit/pdfkit/pull/347
But I just googled it, cannot help more than that.

**Comment by RKushnir** [comment]
I tried updating the bundler, but it still fails for jruby https://travis-ci.org/RKushnir/protobuf/builds/103723823

**Comment by film42** [comment]
@RKushnir I just opened https://github.com/ruby-protobuf/protobuf/pull/279 which [makes travis pass](https://travis-ci.org/ruby-protobuf/protobuf/builds/103726222).

**Pull request merged**
